import { v4 as uuidv4 } from 'uuid';

export const financeData = [
    {
      id: uuidv4(),
      date: '2024-01-01',
      description: 'Salary',
      amount: 5000,
      category: 'Income',
    },
    {
      id: uuidv4(),
      date: '2024-01-03',
      description: 'Groceries',
      amount: -150,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-01-05',
      description: 'Utility Bill',
      amount: -200,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-01-07',
      description: 'Coffee',
      amount: -5,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-01-10',
      description: 'Freelance Project',
      amount: 1200,
      category: 'Income',
    },
    {
      id: uuidv4(),
      date: '2024-01-12',
      description: 'Gym Membership',
      amount: -60,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-01-14',
      description: 'Restaurant',
      amount: -45,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-01-16',
      description: 'Car Repair',
      amount: -350,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-01-18',
      description: 'Dividends',
      amount: 200,
      category: 'Income',
    },
    {
      id: uuidv4(),
      date: '2024-01-20',
      description: 'Insurance Premium',
      amount: -100,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-01-22',
      description: 'Online Course',
      amount: -80,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-01-25',
      description: 'Interest',
      amount: 50,
      category: 'Income',
    },
    {
      id: uuidv4(),
      date: '2024-01-27',
      description: 'Entertainment',
      amount: -70,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-01-29',
      description: 'Fuel',
      amount: -40,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-01-31',
      description: 'Savings Deposit',
      amount: -300,
      category: 'Savings',
    },
    {
      id: uuidv4(),
      date: '2024-02-01',
      description: 'Stock Purchase',
      amount: -500,
      category: 'Investments',
    },
    {
      id: uuidv4(),
      date: '2024-02-03',
      description: 'Freelance Work',
      amount: 800,
      category: 'Income',
    },
    {
      id: uuidv4(),
      date: '2024-02-05',
      description: 'Medical Bill',
      amount: -300,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-02-07',
      description: 'Books',
      amount: -30,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-02-10',
      description: 'Consulting Fees',
      amount: 1500,
      category: 'Income',
    },
    {
      id: uuidv4(),
      date: '2024-02-12',
      description: 'Subscriptions',
      amount: -20,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-02-14',
      description: 'Travel',
      amount: -120,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-02-16',
      description: 'Home Repair',
      amount: -450,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-02-18',
      description: 'Investment Return',
      amount: 250,
      category: 'Income',
    },
    {
      id: uuidv4(),
      date: '2024-02-20',
      description: 'Car Maintenance',
      amount: -150,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-02-22',
      description: 'Online Subscription',
      amount: -15,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-02-25',
      description: 'Affiliate Income',
      amount: 60,
      category: 'Income',
    },
    {
      id: uuidv4(),
      date: '2024-02-27',
      description: 'Personal Care',
      amount: -50,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-02-29',
      description: 'Fitness Equipment',
      amount: -200,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-03-01',
      description: 'Dividend Income',
      amount: 300,
      category: 'Income',
    },
    {
      id: uuidv4(),
      date: '2024-03-03',
      description: 'Pet Expenses',
      amount: -80,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-03-05',
      description: 'Office Supplies',
      amount: -40,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-03-07',
      description: 'Online Course Fee',
      amount: -150,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-03-10',
      description: 'Freelance Payment',
      amount: 2000,
      category: 'Income',
    },
    {
      id: uuidv4(),
      date: '2024-03-12',
      description: 'Professional Membership',
      amount: -100,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-03-14',
      description: 'Dinner Out',
      amount: -70,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-03-16',
      description: 'Household Items',
      amount: -90,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-03-18',
      description: 'Cashback',
      amount: 25,
      category: 'Income',
    },
    {
      id: uuidv4(),
      date: '2024-03-20',
      description: 'Medical Supplies',
      amount: -150,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-03-22',
      description: 'Software License',
      amount: -60,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-03-25',
      description: 'Investment Gain',
      amount: 100,
      category: 'Income',
    },
    {
      id: uuidv4(),
      date: '2024-03-27',
      description: 'Home Improvement',
      amount: -400,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-03-29',
      description: 'Charitable Donation',
      amount: -75,
      category: 'Expenses',
    },
];
