import { v4 as uuidv4 } from 'uuid';

export const financeData = [
    {
      id: uuidv4(),
      date: '2024-01-01',
      description: 'Salary',
      amount: 5000,
      category: 'Income',
    },
    {
      id: uuidv4(),
      date: '2024-01-03',
      description: 'Groceries',
      amount: -150,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-01-05',
      description: 'Utility Bill',
      amount: -200,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-01-07',
      description: 'Coffee',
      amount: -5,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-01-10',
      description: 'Freelance Project',
      amount: 1200,
      category: 'Income',
    },
    {
      id: uuidv4(),
      date: '2024-01-12',
      description: 'Gym Membership',
      amount: -60,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-01-14',
      description: 'Restaurant',
      amount: -45,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-01-16',
      description: 'Car Repair',
      amount: -350,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-01-18',
      description: 'Dividends',
      amount: 200,
      category: 'Income',
    },
    {
      id: uuidv4(),
      date: '2024-01-20',
      description: 'Insurance Premium',
      amount: -100,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-01-22',
      description: 'Online Course',
      amount: -80,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-01-25',
      description: 'Interest',
      amount: 50,
      category: 'Income',
    },
    {
      id: uuidv4(),
      date: '2024-01-27',
      description: 'Entertainment',
      amount: -70,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-01-29',
      description: 'Fuel',
      amount: -40,
      category: 'Expenses',
    },
    {
      id: uuidv4(),
      date: '2024-01-31',
      description: 'Savings Deposit',
      amount: -300,
      category: 'Savings',
    },
  ];
  